# Generated by Django 4.1.3 on 2023-08-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='uname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo'),
        ),
        migrations.AlterModelTable(
            name='paymenthistory',
            table='PaymentHistory',
        ),
    ]
