# Generated by Django 4.1.3 on 2023-08-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_remove_paymenthistory_user_paymenthistory_uname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='uname',
            field=models.ForeignKey(default='uname', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo'),
        ),
    ]
