# Generated by Django 4.1.3 on 2023-08-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_paymenthistory_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='uname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo'),
        ),
    ]
