# Generated by Django 4.1.3 on 2023-08-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_alter_paymenthistory_uname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
