# Generated by Django 4.1.3 on 2023-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_delete_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Topping',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='AdminApp.topping'),
        ),
    ]
