# Generated by Django 4.1.3 on 2023-08-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_topping_product_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
